kafka:
  brokers: "164.52.202.184:9092"
  topic: "entity-change-events-1"
  groupId: "flink-group-1201"
  readFromEarliest: false

iceberg:
  warehouse: "s3a://sc-developer-bucket/"
  catalog-name: "glue_catalog"
  catalog-type: "glue"
  database: "iceberg_db_test"
  table: "ck_orders"

s3:
  endpoint: "https://s3.ap-south-1.amazonaws.com"
  access-key: "ASIATQDQ4KPFQYHEAAJA"
  secret-key: "8bI38NSE8DTe8zs+CYJLn+po3AReUVopBdvMNuaP"
  session-token: "IQoJb3JpZ2luX2VjEK3//////////wEaCmFwLXNvdXRoLTEiRzBFAiEA6fPxQLWTeEaCavEXaCXhxUFmlv0mE9RvHqri4X8NrC8CICMAH2dgX8mxbC6gS5q+LaTBOZo0MKv3I8YPJvFGfn+5KpADCHYQABoMMjQwNzU0OTA2MDU5IgyPJmdc/PGuZss6k8cq7QIBftI0CdEe1GtB8TwNlBSE8kHk3K0DKmP/lti18BqGlqp2VRROPKadkcswrqjDKis3ZWRjVMJUSqsHjJbFH+ymUYpZjwKTbl3uqAppb7lY777SuXCzqOgX6e0P5I8lkqJe/yGJHqqX8D6DaoJMyzSGg64ezRJhe8AA4guU1VaDeVFLs2W/4+gIlFzYB4BXZV7y5P2hjanGb7+ZEXuovwZV9g44KhnKJHfXPFBlq6u+PQsVpR01KXNGW3lHr76EfVnIztHcKgwqRafRQifoOisGqTSyDpaUlNpDdCxuEfd5wt5V5wIuOXR0LOO7SM3PXsgFbL2k5rGwqNn4cd07ViO/v/oq4/NTt5OHhcfwOu/Rn+1+WJinh8avGL+AeZWSE5ZNbJ5NbkV3smVR6v30M1411cAb44sAzq5AZxq5HYzZyUTozEMdpJWxlWmRBqUUzpeAVQUoZBx81L7qp1u/Zk8DmtOFFHBlMs5Ee5iBqDDsufnKBjqkAaVysGsR6PKRycBiO81LSgsBXHAPe0KV/syf++LVKAZ0/rFxtrSC8MLJR+uGA0zJcTzOnZxnL2HkILl7eR4iSNrFhA4WrM7GQbOG3Sexze62grovMduvJ1m1gzNbCNMQ8genJXrjDh1Jko+vdKVWeSTTyfFF9ExuI0XzpDR9N7lyHsLGT7uS9fuDSJX3lMZCqQbUYDYEzsMFOJh4Ll5FFpQ0yyrE"
  path-style-access: false
