kafka:
  brokers: "164.52.202.184:9092"
  topic: "entity-change-events-1"
  groupId: "flink-group-1211111111111111"
  readFromEarliest: false

iceberg:
  warehouse: "s3a://sc-developer-bucket"
  catalog-name: "my_catalog"
  database: "db1"
  table: "orders"

s3:
  endpoint: "https://s3.ap-south-1.amazonaws.com"
  access-key: "ASIATQDQ4KPFRVYKO5SZ"
  secret-key: "PyhhFTz85nFPn3E3g7ufxx8iY5jAfjjzcLYW4fyw"
  session-token: "IQoJb3JpZ2luX2VjEML//////////wEaCmFwLXNvdXRoLTEiRjBEAiA37SoRTHLVaGNNAAhk2V81oygvSbhzUokz7znXv9rJLwIgNo9fjPtxrGZEZxgms9Kchxh+ovTXSeHDnKUEh+K1kLYqmgMIi///////////ARAAGgwyNDA3NTQ5MDYwNTkiDPdzFxgwfL9Mlt6ozCruAoxNXGt2qNe7s5BeaIhdUooO/aW50uELk1+ygCxDO7FjYkRINWRqWleksqbKLthJRPm511haH2cGUqgOYiJpu4gufzzI5eF6a/pcFd8O9j9OnJcsREARYXse/cL5CEHSyBRueFvJ1DeUUW9H6X3j9N5Cm44wMWAduQYEap868H5zUq7dWlM5TYFA60YuAJQd+ymLqZA6hgOcUWuWVe5T62A2r+zZOBxGKpqdfPtGO0eQaeQGm4sLcTS18DIDvgpaTCEcvcdu3NmVLlLthRd+1gNHnFiyWNxFLhl6ciH2wcIe5Cr3Rpi6PgE/tSaoZqtJTWwA9fZdvdZCvZOinQ3YgkW97pAfjqNaSchayQilqS5yM2vpPZ31dz6mAsQ70+n41tRui0Kx83TMJspRQ2Xwf5NABK8CJrxil7YTMndYqmg5ywCNajmgpVbhXDzE3cl4lHX9F9WRWmuyGkERSupJrJ4bhF3V/pVmXlQP1Uln/TDHif7KBjqlAat697NZ1iwIsRY5/fYlalqrvnUnIAEMA5c5k8meeIcsDXEaTZscSXoMsd74kvQGkgagSCD8NckbuxjfdF9pk0TBUVS9YXJxEB7C8MuhTQ/PR53/X8JGosvd5mDMZd87q7su4NrURwz213VOChAvcuYifJRjTLFdp/G+LOrE2T7FBNGYOd3hbpaz1mr7X5mXxP6VexxiJNeXppTtT+HUpOipGE6hkw=="
  path-style-access: false
