kafka:
  brokers: "164.52.202.184:9092"
  topic: "entity-change-events-1"
  groupId: "flink-group-121181a1"
  readFromEarliest: false

iceberg:
  warehouse: "s3a://sc-developer-bucket"
  catalog-name: "my_catalog"
  database: "db1"
  table: "orders"

s3:
  endpoint: "https://s3.ap-south-1.amazonaws.com"
  access-key: "ASIATQDQ4KPF7VTUECLU"
  secret-key: "N+YE6LOE1VaxX6FbzEYhb1VSjYO+j8tqZKLsN6Om"
  session-token: "IQoJb3JpZ2luX2VjEL3//////////wEaCmFwLXNvdXRoLTEiRzBFAiAAhFHlRlBNjCY/b2rg+DO2jaHaT9W5Sf8YA2XF63IWKwIhAJ5xCogGQl9cDh3hAqcYFNP5sAmpj0ffeY0JBG8PuTJQKpoDCIb//////////wEQABoMMjQwNzU0OTA2MDU5IgzFE/s2VFyUFuT7Sh0q7gJdns9/zKKxJbtotEFasW5ZX2RY4xEHsQeCPc7WaRz5+3pl5JVrAGD2Ys5CsT3fdEoIP1OiHZQgmim7TZMeufKZU9w6WSMVNpmnH1MweDYyHGD/jDkAe2snvWExO+7hjHadYjDFoUz0BWpovq78vDELtQK2ifWjj+Cy5+UXb9SePKOPCdvGAzLW4pHBJTLZot5WYEXQmW2riHUnfzulmucM6MmK6rLjcZmoXGzJNmLUGUXZZGYVY1+/S0iOj5Zy6iw9J6h3xZegl2rLtkynMsXX9y+brPVbpZgnQLD+YDIC6lw37bbpoZram68nrSi8UEAzpo6Xnk1zM/AVypH6amgtTspwn7koc3uGHE9C7T+Koxt3HuehgOuYSM0//e0P0cWKQWyzcRFcgEZoH12WgTlJw6OVm5DTfqbkwNWrb0OGs0c93DLiwBRXT5q0boYzYNhOYVu/EwrrnI1CCPRzBFJjjVKF+YBpep/ZkEruIqQw/u38ygY6pAFuY01eCHEYSTtcmI8+vnnKDjIHqsUy3mpOxO9g7q+LpaQOV06pvyobHLKXhMntgzs5KRxMNuOccY2eokHTJi+G7WMMqfAsP2TuVSu2F5UMOOeVVmD7a5AHLHkin3X5OuaWwRassZpm6KOhhoK5R/V4Jr4Z7gYPO2GyuQ6zRqp2PBG0Sjf44aErYBn4mQf9zeUz46GamKZmr1fyftspxZzWvQHwDw=="
  path-style-access: false
