entities:
  - entity-name: "Order"
    lobs:
      - "simamyuat"
    kafka-topic: "simamyuat-bulk-reject-order-invoice-update-event"
    kafka-broker: "164.52.202.184:9092"
    group-id: "orders"
    iceberg-table: "orders"
    output-class: "OrderIcebergEntity"
    runtime-minutes: 0.1
    fields:
      - field-path: "orderId"
        type : "String"
        sub-fields: null
      - field-path: "outletCode"
        type: "String"
        sub-fields: null
      - field-path: "creationTime"
        type: "String"
        sub-fields: null
      - field-path: "status"
        type: "String"
        sub-fields: null
      - field-path: "orderDetails"
        type: "List"
        sub-fields:
          - field-path: "skuCode"
            type: "String"
            sub-fields: null
          - field-path: "initialAmount"
            type: "String"
            sub-fields: null
          - field-path: "initialQuantity"
            type: "String"
            sub-fields: null
    partition-keys:
      - "status"
      - "creationTime"
    enabled: true
